CREATE TABLE integer_pk(id INTEGER PRIMARY KEY);
CREATE TABLE descending_pk(id INTEGER PRIMARY KEY DESC);
CREATE TABLE text_pk(id TEXT PRIMARY KEY);
CREATE TABLE strict_pk(id TEXT PRIMARY KEY) STRICT;
CREATE TABLE composite_pk(first TEXT, second TEXT, PRIMARY KEY(first, second)) WITHOUT ROWID;
